.PHONY: rejection

rejection:
	gfortran -o e rejection.f90

transformation:
	gfortran -o e transformation.f90

histogram:
	gfortran -o e histogram.f90

boxmuller-histogram:
	gfortran -o e boxmuller-histogram.f90
	
boxmuller-kernel:
	gfortran -o e boxmuller-kernel.f90

run:
	./e
